// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InsertSiteVisit_TB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertSiteVisit_TB));
        
        string IMigrationMetadata.Id
        {
            get { return "202308081359073_Insert-SiteVisit_TB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
